import Head from 'next/head'
import { useState } from 'react'


export default function Home() {

  const [data, setData] = useState({
    name: '',
    email: ''
  })

  const valueInput = e => setData({...data, [e.target.name]: e.target.value})

  const addUser = (e) => {

    e.preventDefault()
    console.log("Enviar para API")
    console.log(data.name)
    console.log(data.email)
  }
  return (
    <>
      <Head>
        <title>React Form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>Cadastrar Usuário</h2>
          <form onSubmit={addUser}>
            <label>Nome:</label>
            <input type="text" name="name" placeholder="Digite seu nome" onChange={valueInput} value={data.name}/><br /><br />

            <label>Email:</label>
            <input type="email" name="email" placeholder="Digite seu melhor email" onChange={valueInput} value={data.email}/><br /><br />


            <button type="submit">Enviar</button><br />
          </form>
      </main>
    </>
  )
}
